### ISSUE TITLE
Coursera Web scraping bug

### ISSUE THREAD

**Issue by utkarshsharma1** [Siddharth1698/Coursu#5]
![image](https://user-images.githubusercontent.com/28705599/85768700-ebc69b00-b736-11ea-97ee-8a204348a5c8.png)

I am facing this issue while scraping.

**Comment by Siddharth1698** [comment]
did u make any changes to code or rand it same way?

**Comment by Siddharth1698** [comment]
There are few bugs here.. please check another of my repo: https://github.com/Siddharth1698/Coursera-Course-Dataset
And if u have issue let me know there.
